import type { Metadata } from "next";
import "../globals.css";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import { Player } from "./Player/page";
import { SideBar } from "@/components/SideBar";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="dark h-screen w-full flex flex-col">
        <Header />
        <ResizablePanelGroup direction="horizontal">
          <ResizablePanel minSize={12} defaultSize={12}>
            <SideBar />
          </ResizablePanel>
          <ResizableHandle />
          <ResizablePanel>{children}</ResizablePanel>
        </ResizablePanelGroup>
        <Player />
      </body>
    </html>
  );
}
