import type { Metadata } from "next";
import "../globals.css";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import { SideBar } from "@/components/SideBar";
import { Header } from "@/components/Header";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "SoundByte",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  Player,
}: Readonly<{
  children: React.ReactNode;
  Player: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <ResizablePanelGroup direction="horizontal">
        <Toaster />
        <SideBar />
        <ResizableHandle />
        <ResizablePanel>{children}</ResizablePanel>
      </ResizablePanelGroup>
      {Player}
    </>
  );
}
